import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import React, { useState, useCallback, useMemo } from 'react'
import Head from 'next/head'
import Popup from '../src/components/Popup'
// import Image from 'next/image'
import { DiaryProvider } from '../src/providers/diary'

const Home: NextPage = () => {
  const [diary, setDiary] = useState('')
  const [diaryObj, setDiaryObj] = useState<IDiary | null | undefined>(null)
  const router = useRouter()
  const disabled = useMemo(() => {
    if (diary == '' || diaryObj) return true
    else return false
  }, [diary, diaryObj])

  const saveDiary = async () => {
    let strArr: string[] = diary.split('')
    // char !== '　' ||
    // char !== '\r\n' ||
    // char !== '\n' ||
    // char !== '\r' ||
    // char !== '\t'
    let a2: Array<string | RegExp> = strArr
    if (a2.filter(char => char !== ' ').length == 0) {
      alert('不能输入空格')
      return null
    }
    try {
      const { msg, diaryObj } = await DiaryProvider.saveDiary({
        content: diary,
      })
      //拿到了返回的日记对象（刚保存的那条）（无错误）
      if (diaryObj !== undefined) {
        setDiaryObj(diaryObj) //激活Popup组件
        document.querySelector('textarea')!.value = ''
      } else console.log(msg) //'日记保存失败。'
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <div className={`${diaryObj && diaryObj._id && 'relative'}`}>
      <Head>
        <title>SideProject02</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {diaryObj && diaryObj._id && (
        <Popup _id={diaryObj._id} setDiaryObj={setDiaryObj} />
      )}

      <div className='h-screen w-screen flex flex-col justify-center items-center'>
        <textarea
          disabled={diaryObj ? true : false}
          autoFocus
          onChange={e => setDiary(e.target.value)}
          className='w-[40vw] h-[50vh] rounded outline-none resize-none
        border-transparent border-solid border-2 text-2xl'
        />
        <div className='flex mt-10 gap-20'>
          <button
            className='border-2 border-solid border-transparent
        bg-opacity-40 bg-gray-400 rounded-md w-[10vw] h-[7vh]
        text-xl disabled:opacity-50 disabled:cursor-not-allowed'
            disabled={disabled}
            onClick={saveDiary}>
            烂&nbsp;笔&nbsp;头
          </button>
          <button
            disabled={diaryObj ? true : false}
            className='text-xl'
            onClick={() => router.push('/memories')}>
            好&nbsp;记&nbsp;性
          </button>
        </div>
      </div>
    </div>
  )
}

// Home.getInitialProps = async () => {}

export default Home
